server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/home_energy_tracker
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: "localhost"
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: usage-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: alertingEvent:com.my_space.kafka.event.AlertingEvent
