server:
  port: 8083

spring:
  kafka:
    bootstrap-servers: localhost:9094
    template:
      default-topic: energy-usage
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

simulation:
  ingestion-endpoint: "http://localhost:8083/api/v1/ingestion"
  requestsPerInterval: 1000
  interval-ms: 5000
  parallel-threads: 10
