server:
  port: 8084

spring:
  kafka:
    bootstrap-servers: localhost:9094
    template:
      default-topic: "energy-alert"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: usage-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: energyUsageEvent:com.my_space.kafka.event.EnergyUsageEvent

influx:
  url: "http://localhost:8072"
  token: "my-token"
  org: "my-space"
  bucket: "usage-bucket"

endpoint:
  device-service-url: "http://localhost:8081/api/v1/device"
  user-service-url: "http://localhost:8080/api/v1/user"
